### ISSUE TITLE
Could not match UI with screenshots in doc

### ISSUE THREAD

**Issue by FrancisVila** [jenkinsci/git-push-plugin#35]
### Describe your use-case which is not covered by existing documentation.

Here is the beginning of the doc. I was confused because my job was created as Pipeline, and lacked the features shown in the doc screenshots and instructions.

## [](https://plugins.jenkins.io/git-push/#plugin-content-introduction)Introduction

This plugin allows to perform a git push as a post build step via [Git Plugin](https://plugins.jenkins.io/git)[](https://plugins.jenkins.io/git-push/#plugin-content-getting-started)

In details, the plugin will pull then push (tags included) to the selected remote branch.
Getting started
 - - - - - - - _Add this in:_ **The instructions below are based on a Jenkins job created as a Freestyle project.**
_(if it is possible to do the same with other typesof job, add that in)_

Open the Jenkins job configuration.

**Comment by reda-alaoui** [comment]
Please provide a pull request
